# Generated by Django 4.0.3 on 2022-04-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('evaluate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('student_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=200)),
                ('prize', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='in_Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=200)),
                ('student_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='in_English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('student_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='in_Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('student_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200)),
                ('short', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('leader_name', models.CharField(max_length=200)),
                ('work_time', models.CharField(max_length=200)),
                ('payment', models.FloatField()),
                ('house', models.CharField(max_length=200)),
                ('rent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('plan', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('qs_rank', models.IntegerField()),
                ('enrollment', models.IntegerField()),
                ('final_number', models.IntegerField()),
                ('enrollment_for_bupt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('GPA', models.FloatField()),
                ('Rank', models.CharField(max_length=200)),
                ('scholarship', models.CharField(max_length=200)),
                ('Hand_in_date', models.DateField()),
                ('get_offer_date', models.DateField()),
                ('major', models.CharField(max_length=200)),
                ('program_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
            ],
        ),
    ]
