# Generated by Django 4.0.3 on 2022-03-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_Name', models.CharField(max_length=200)),
                ('qs_rank', models.IntegerField()),
                ('enrollment', models.IntegerField()),
                ('enrollment_for_bupt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('GPA', models.FloatField()),
                ('Rank', models.CharField(max_length=200)),
                ('scholarship', models.CharField(max_length=200)),
                ('Hand_in_date', models.DateField()),
                ('get_offer_date', models.DateField()),
            ],
        ),
    ]
