# Generated by Django 4.0.3 on 2022-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoAbroad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
