# Generated by Django 4.0.3 on 2022-05-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoAbroad', '0002_student_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('student_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='practice',
        ),
        migrations.AlterField(
            model_name='agent',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='evaluate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='english',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_competition',
            name='competition_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='in_competition',
            name='student_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='in_english',
            name='student_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='in_english',
            name='test_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='in_practice',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='short',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='house',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='leader_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='awards',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='nation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.teacher'),
        ),
        migrations.AlterField(
            model_name='school',
            name='enrollment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='enrollment_for_bupt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='final_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='qs_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Hand_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='get_offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.major'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.school'),
        ),
    ]
