# Generated by Django 4.0.3 on 2022-05-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoAbroad', '0003_choice_agent_remove_student_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.practice'),
            preserve_default=False,
        ),
    ]
