# Generated by Django 4.0.3 on 2022-05-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoAbroad', '0004_student_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='practice',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.practice'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='GoAbroad.teacher'),
        ),
    ]
